--- 
- 
  hosts: localhost
  name: "Hello World!"
  tasks: 
    - 
      name: "Installing pip modules for using vault lookup"
      pip: "name={{item}}"
      with_items: 
        - hvac
        - "hvac[parser]"
    - 
      name: "Hello World!"
      shell: "echo \"Hi! Tower is working! version 3\""
    - 
      debug: 
        msg: "{{ env | default('default_value') }} {{ extra_vars | default('default_value') }}"
      name: "What's my name again?" 
