--- 
- 
  hosts: localhost
  name: "Hello World!"
  vars:
    - key_data: "{{ lookup('hashi_vault', 'secret=secret/data/test:data token={{ VAULT_TOKEN }} url={{ VAULT_ADDR }}')}}"
 
  tasks: 
    - 
      name: "Installing pip modules for using vault lookup"
      pip: "name={{item}}"
      with_items: 
        - hvac
        - "hvac[parser]"
    - 
      name: "Hello World!"
      shell: "echo \"Hi! Tower is working! version 3\""
    - 
      debug: 
        msg: "{{ key_data | default('default_value') }} {{ VAULT_TOKEN | default('default_value') }}"
      name: "What's my name again?" 
      
    - 
      debug: msg="{{ lookup('env','HOME') }} is an environment variable"

      

