--- 
- 
  hosts: localhost
  name: "Hello World!"
  vars:
    - key_data: "{{ lookup('hashi_vault', 'secret=secret/data/test:data token={{ VAULT_TOKEN }} url={{ VAULT_ADDR }}')}}"
 
  tasks: 
    - debug: msg="{{ lookup('env','HOME') }} is an environment variable"
    
    - debug: msg="{{ lookup('env','VAULT_TOKEN') }} is an environment variable"

      

