--- 
- 
  hosts: localhost
  name: "Hello World!"
  vars:
    - VAULT_TOKEN: "{{lookup('env','VAULT_TOKEN')}}"
    - VAULT_ADDR: "{{lookup('env','VAULT_ADDR')}}"
    - key_data: "{{ lookup('hashi_vault', 'secret=secret/data/test:data token={{ VAULT_TOKEN }} url={{ 'VAULT_ADDR' }}')}}"
 
  tasks: 
    - debug: msg="{{ key_data | default('default_value') }}"
    
    - debug: msg="{{ lookup('env','VAULT_TOKEN') }} is an environment variable"

      

